//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Inimigo input actions 1.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inimigoinputactions1: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inimigoinputactions1()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inimigo input actions 1"",
    ""maps"": [
        {
            ""name"": ""Inimigo"",
            ""id"": ""88e5143d-94d9-46c6-9c11-4c2fa59aca4e"",
            ""actions"": [
                {
                    ""name"": ""Movimento"",
                    ""type"": ""Value"",
                    ""id"": ""0c5118fa-1829-4043-a413-b10cc662acac"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Atacar"",
                    ""type"": ""Button"",
                    ""id"": ""0c0b5a1a-d128-41fe-ac3d-a5dcab102c05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interagir"",
                    ""type"": ""Value"",
                    ""id"": ""13cbdc7a-90cd-46c9-b5d1-9734d49bf18f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ControleCamera"",
                    ""type"": ""Value"",
                    ""id"": ""64b99652-3784-4538-b148-f35e7e44dd20"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""e3d871ae-c324-40e0-9272-45d6b9e4d970"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""988c3ba0-8a37-4243-bf95-0b237eaf0cec"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b42cf4d3-054a-49cd-bfac-6fd1edd91a82"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f2bf904c-645e-4d7e-8218-bc23b4c4a99e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""348629d4-41fe-4164-94f5-68805f5b32f8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""cff875fc-0b0f-4592-a991-cb6802e926e0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""759b9a5e-32fd-4973-886a-fd89463b9739"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""52144ee4-b40b-4f12-a26b-9c439ededc27"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""659e5464-a75c-421b-b7ad-ef910a72faa3"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3bb52d01-9e31-4d93-bc03-964ba77ef7d0"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""aa80a75e-eb4e-47ba-ade5-577342437738"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interagir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e397c43a-80cf-49ae-902d-d490bbd7f6af"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interagir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a90d33d6-473c-4f20-881b-27e98bb85ef9"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Atacar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27a968da-fb4a-47ec-bd1c-8340d4bca4e4"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Atacar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7731d3a-c3d7-4a5c-8052-fa80e697f0a8"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Atacar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05dbfa78-827a-4cff-abdf-60412ad545eb"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControleCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Inimigo
        m_Inimigo = asset.FindActionMap("Inimigo", throwIfNotFound: true);
        m_Inimigo_Movimento = m_Inimigo.FindAction("Movimento", throwIfNotFound: true);
        m_Inimigo_Atacar = m_Inimigo.FindAction("Atacar", throwIfNotFound: true);
        m_Inimigo_Interagir = m_Inimigo.FindAction("Interagir", throwIfNotFound: true);
        m_Inimigo_ControleCamera = m_Inimigo.FindAction("ControleCamera", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Inimigo
    private readonly InputActionMap m_Inimigo;
    private List<IInimigoActions> m_InimigoActionsCallbackInterfaces = new List<IInimigoActions>();
    private readonly InputAction m_Inimigo_Movimento;
    private readonly InputAction m_Inimigo_Atacar;
    private readonly InputAction m_Inimigo_Interagir;
    private readonly InputAction m_Inimigo_ControleCamera;
    public struct InimigoActions
    {
        private @Inimigoinputactions1 m_Wrapper;
        public InimigoActions(@Inimigoinputactions1 wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movimento => m_Wrapper.m_Inimigo_Movimento;
        public InputAction @Atacar => m_Wrapper.m_Inimigo_Atacar;
        public InputAction @Interagir => m_Wrapper.m_Inimigo_Interagir;
        public InputAction @ControleCamera => m_Wrapper.m_Inimigo_ControleCamera;
        public InputActionMap Get() { return m_Wrapper.m_Inimigo; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InimigoActions set) { return set.Get(); }
        public void AddCallbacks(IInimigoActions instance)
        {
            if (instance == null || m_Wrapper.m_InimigoActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InimigoActionsCallbackInterfaces.Add(instance);
            @Movimento.started += instance.OnMovimento;
            @Movimento.performed += instance.OnMovimento;
            @Movimento.canceled += instance.OnMovimento;
            @Atacar.started += instance.OnAtacar;
            @Atacar.performed += instance.OnAtacar;
            @Atacar.canceled += instance.OnAtacar;
            @Interagir.started += instance.OnInteragir;
            @Interagir.performed += instance.OnInteragir;
            @Interagir.canceled += instance.OnInteragir;
            @ControleCamera.started += instance.OnControleCamera;
            @ControleCamera.performed += instance.OnControleCamera;
            @ControleCamera.canceled += instance.OnControleCamera;
        }

        private void UnregisterCallbacks(IInimigoActions instance)
        {
            @Movimento.started -= instance.OnMovimento;
            @Movimento.performed -= instance.OnMovimento;
            @Movimento.canceled -= instance.OnMovimento;
            @Atacar.started -= instance.OnAtacar;
            @Atacar.performed -= instance.OnAtacar;
            @Atacar.canceled -= instance.OnAtacar;
            @Interagir.started -= instance.OnInteragir;
            @Interagir.performed -= instance.OnInteragir;
            @Interagir.canceled -= instance.OnInteragir;
            @ControleCamera.started -= instance.OnControleCamera;
            @ControleCamera.performed -= instance.OnControleCamera;
            @ControleCamera.canceled -= instance.OnControleCamera;
        }

        public void RemoveCallbacks(IInimigoActions instance)
        {
            if (m_Wrapper.m_InimigoActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInimigoActions instance)
        {
            foreach (var item in m_Wrapper.m_InimigoActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InimigoActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InimigoActions @Inimigo => new InimigoActions(this);
    public interface IInimigoActions
    {
        void OnMovimento(InputAction.CallbackContext context);
        void OnAtacar(InputAction.CallbackContext context);
        void OnInteragir(InputAction.CallbackContext context);
        void OnControleCamera(InputAction.CallbackContext context);
    }
}
